name: eversys
favicon: null
layout_spectrum: 0.57032
typography_spectrum: 0.10787
title: Piąte urodziny Eversysu
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#313131'
    - '#ffffff'
    - '#d2d2d2'
    - '#a5a5a5'
  brandStrength: 0.2717791183385998
  lightness: 0.32976499758660793
  saturation: 0.605941177578643
  rhythmicContrast: 0.9457700969651341
purpose: []
